name: Publish on Marketplace

on:
  push:
    branches: [master]

jobs:
  publish:
    name: Publish on Marketplace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          
      - name: Install VSCE
        run: npm i -g vsce
      - name: Publishing
        run: vsce publish minor -p ${{ secrets.VSCE_TOKEN }}
