name: Publish on Marketplace

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish on Marketplace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Publishing
        run: npx vsce publish ${{ github.event.release.tag_name }} -p ${{ secrets.VSCE_TOKEN }}
